name: questions_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: ../authentication_repository

  cloud_firestore: ^1.0.1
  rxdart: ^0.24.0
  equatable: ^2.0.0
  firebase_core: ^1.0.1
  sembast: ^3.0.1
  path_provider: ^2.0.1
